apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: limits-matthijs
spec:
  containers:
    - name: cpu-demo-ctr
      image: vish/stress
      resources:
        limits:
          cpu: "1" # We may "burst" to use 1 full CPU core
        requests:
          cpu: "0.5" # 0.5 CPU is AWLAYS reserved for us (no other app can claim this)
      args:
        - -cpus
        - "2" # The "stress" application will try to use 2 CPU cores